language: csharp
mono: none
dotnet: 3.1.401
addons:
    homebrew:
        update: true
        brewfile: true

os:
    - linux
    - osx
dist: xenial

before_script:
    # Add .NET Core global tools to PATH, so that protoc can locate protoc-gen-delphi
    - export PATH=$PATH:$HOME/.dotnet/tools
    - |
        if [ "$TRAVIS_OS_NAME" = "linux" ]; then
            curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
            unzip protoc-3.13.0-linux-x86_64.zip -d $HOME/.local
            export PATH="$PATH:$HOME/.local/bin"
        fi
    - |
        if [ "$TRAVIS_OS_NAME" = "linux" ]; then
            curl -LO http://launchpadlibrarian.net/494661083/fp-units-rtl-3.2.0_3.2.0+dfsg-8build2_amd64.deb
            sudo dpkg -i fp-units-rtl-3.2.0_3.2.0+dfsg-8build2_amd64.deb
            curl -LO http://launchpadlibrarian.net/494661053/fp-compiler-3.2.0_3.2.0+dfsg-8build2_amd64.deb
            sudo dpkg -i fp-compiler-3.2.0_3.2.0+dfsg-8build2_amd64.deb
        fi

script:
    - make test
